name: cracker_app
description: Crack Kraków with the Cracker app!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1

  cupertino_icons: ^1.0.0
  english_words: ^3.1.5
  flutter_appauth: ^0.9.2+6
  flutter_secure_storage: ^3.3.5
  geolocator: ^6.0.0
  google_maps_flutter: 1.0.6
  graphql_flutter: ^3.0.0
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true